---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cluster-config/cluster-rolebinding

patches:
  - target:
      kind: ClusterRoleBinding
    patch: |-
      - op: add
        path: /metadata/name
        value: developer-cluster-view-crb
      - op: add
        path: /roleRef/name
        value: cluster-view
      - op: add
        path: /subjects/0/name
        value: security-team-group
