---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-common
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: lab-clusterset
              requeueAfterSeconds: 3600
          - git:
              repoURL: https://github.com/Vikaspogu/acm-demo.git
              revision: master
              directories:
                - path: managedclusters/lab/common/*
  template:
    metadata:
      name: 'lab-{{name}}-{{path.basename}}'
    spec:
      destination:
        server: "{{server}}"
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: "{{path}}"
        repoURL: "https://github.com/Vikaspogu/acm-demo.git"
        targetRevision: "master"
