---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managedclusters-lab-application-set
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/Vikaspogu/acm-demo.git
        revision: main
        directories:
          - path: managedclusters/argo-applications/lab/*
  template:
    metadata:
      name: 'managedclusters-lab-{{path.basename}}'
    spec:
      destination:
        server: "https://kubernetes.default.svc"
      project: default
      syncPolicy:
        automated:
          prune: true
      source:
        path: "{{path}}"
        repoURL: "https://github.com/Vikaspogu/acm-demo.git"
        targetRevision: "main"
