apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: dummy
  labels:
    name: dummy
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: lab-clusterset
  annotations: {}
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: dummy
  namespace: dummy
spec:
  clusterName: dummy
  clusterNamespace: dummy
  clusterLabels:
    name: dummy
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: lab-clusterset
  applicationManager:
    enabled: true
    argocdCluster: false
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
